[gcp_service_account]
type = "service_account"
project_id = "streamlit-sheets-test-483420"
private_key_id = "e4c28a5937db5b86e2e71b28802e69405e5202c9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVe3lgR0E1mUlX
kZK5yMMyXEJo7halPPVmoqRHB2zVUQ2JXyGGe8rXFCzTXKw5IcRvOV4MOxbC1Neq
0mDrP626Ogj3IYDi3XsnoshUpLz2ieEn9cvA/Fa7eQkjDMjziAq1yQ0oP7r6D/uI
uSywFFnGbzdmrSvPT8wDsm99XaIlO1erESnCfKRkZEGRrrnx7hWMV5KcRdLUHfm5
q7Iz/5RgSRW2yWNb5Jx3xNV7aqsFphasVwd4QE9IoWPCvfjxCCUm9gs+JLnjbs7t
eInYEX1PeB7+L0PwItaNh1ljeROHCeNJg9DQdTfjFHYZatgZlC3sTVkhQrXZs3lg
A7eeJC0BAgMBAAECggEARkSyVGt6gG8r1nHUlugEtk4/W6McWxWySEqJTeh0JTzC
T8K7+EOGIR/XSI5mWT8B38UIbFh0hSbXsPHPZJbdHE8+uqlxtHOn+oRfhsagG4bK
JGY7n18fiGZHwMW4Sx625ih6OmLnCrjrpaRimO0gHJNYaDhcgUpCHbTKCxUybSxl
fa10AKKImfiKA/MhW08Gci9DDemZaDwFONQfxLdBt2xSj/+/0SFkwCEF5TCLDJYR
yBpV4ISSm5lxBFan9TYoSC/x5BziKl+nAZV/HQDKJlCOo+mSGcWvqx3VlSSlz8ea
/dZzi7OSZ1DN8Rkkpo++ar0lLLOzp57nSbuTSsanNwKBgQDPC9h/ED7fOLuihD2f
ty4nDFIaHtarGpF5uXQnnNKFdNHVzPy6nqgKJySLFjqmjvCZ0vbs9nXfX+yNonTL
ykTq1IuMARzjugRAfGKTZCrsVwkX3YyE4cQQeiT2nkGNH5OP4TIRaPghCSdJGtjD
9eT0QUZNYJlBSxj/6REp8QGSqwKBgQC402GvmjWdz9Cfx5odzZt//PSYjSaRTfwn
Np0BdzzTkQb6V5NqVroRuhLRgBYij2u/su4FM8WRDxnNUugpqIZ/JvVvGK192DL3
O6NUSRTtxZwtxIaGzh8kmYxJIH8kabxPzCPAIDyGxVu6xDPsh5i7LsKXc6hEqV9d
SzK+0RZfAwKBgGnRfRHb5LZDkaqK+c/iWGU+p8uPzVlf19All5cTUIlC3mfuP5DF
u86MmOG5N7qevZtwtiEACdhjd0wgJp9tPnHitXuVqgU9siSfLeZ0wHdQOGaJJeNY
W9OsCa49zfTpmYpkpyk8w+xmeDylyvnEeALaRasQXuN/FUTeApa0BYDHAoGAc+Ou
+9GgztwQfy9D1m4mk6EDqWfQCAozEk9vMQ0X6byk+HHTMDlDIHxg8lXzCyaMtD24
ezCUL7mdPx4+DmjqNG40NL3vgtn+UwFlDyNn6RMgM55nj71Mz8Ersmqa7jUSa6Kf
xAcyjHrRYpFF0YjQXoYaY6aUmsDs1+2f2v/1nAsCgYA5+765te5bNoKW7qgbOFOO
mJizqTloOvnCOWQw21pzsP02i7MFLkITRbMSGbJE3KxTm8BzOLoD2EBXC1qmG2kw
ytPXVEX93493iuk6l9SnBG6NkwtCC+xlRSUnwbyIDLBaTZVL9jwrX9O4T/Y+fMwT
1lw2fgkLWNjbBTUIKaLS3Q==
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets@streamlit-sheets-test-483420.iam.gserviceaccount.com"
client_id = "100459304116183409380"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets%40streamlit-sheets-test-483420.iam.gserviceaccount.com"
universe_domain = "googleapis.com"